# Generated by Django 4.2.11 on 2024-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بازیگر')),
                ('image', models.TextField(verbose_name='عکس بازیگر')),
            ],
            options={
                'verbose_name': 'بازیگران',
                'verbose_name_plural': 'بازیگران',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ژانر فیلم')),
            ],
            options={
                'verbose_name': 'ژانر فیلم',
                'verbose_name_plural': 'ژانر فیلم',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=150, verbose_name='نام فیلم به انگلیسی')),
                ('persian_name', models.CharField(max_length=150, verbose_name='نام فیلم به فارسی')),
                ('type', models.CharField(choices=[('0', 'فیلم'), ('1', 'سریال')], max_length=1, verbose_name='نوع')),
                ('director', models.CharField(blank=True, max_length=100, null=True, verbose_name='کارگردان')),
                ('writer', models.CharField(blank=True, max_length=100, null=True, verbose_name='نویسنده')),
                ('story_line', models.TextField(blank=True, null=True, verbose_name='خلاصه داستان')),
                ('views_count', models.CharField(max_length=10, verbose_name='تعداد بازدید')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='تگ')),
                ('imdb_rate', models.CharField(max_length=3, verbose_name='امتیاز IMDB')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='سال تولید')),
                ('baner', models.TextField(blank=True, null=True, verbose_name='پوستر فیلم')),
                ('tizer', models.TextField(blank=True, null=True, verbose_name='تیزر فیلم')),
                ('box_office', models.CharField(blank=True, max_length=100, null=True, verbose_name='باکس افیس')),
                ('prices', models.TextField(blank=True, null=True, verbose_name='جوایز و افتخارات')),
                ('users_rate', models.CharField(blank=True, max_length=6, null=True, verbose_name='امتیاز کاربران')),
                ('actors', models.ManyToManyField(blank=True, null=True, related_name='movies', to='movie.actor', verbose_name='بازیگران')),
                ('genre', models.ManyToManyField(related_name='movie_genre', to='movie.genre', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='پوستر فیلم')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_movie', to='movie.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
    ]
