# Generated by Django 4.2.11 on 2024-04-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_userdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDashboard',
        ),
    ]
