# Generated by Django 4.2.11 on 2024-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_delete_userdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('0', 'اکشن'), ('1', 'انیمیشن'), ('2', 'عاشقانه'), ('3', 'ماجراجویی'), ('4', 'سایر')], default='4', max_length=1, verbose_name='ژانر فیلم'),
        ),
    ]
