# Generated by Django 4.2.11 on 2024-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('0', 'فیلم'), ('1', 'سریال')], default='0', max_length=1, verbose_name='نوع'),
        ),
    ]
