# Generated by Django 4.2.11 on 2024-05-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='عکس بازیگر'),
        ),
    ]
