# Generated by Django 4.2.11 on 2024-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='views_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد بازدید'),
        ),
    ]
