# Generated by Django 4.2.11 on 2024-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_genre_name_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, null=True, verbose_name='پوستر فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='baner',
            field=models.TextField(blank=True, null=True, verbose_name='بنر فیلم'),
        ),
    ]
